# helm-chart/templates/clusterrole.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-drift-agent.fullname" . }}
rules:
  - apiGroups: ["", "apps", "batch", "extensions"]
    resources: ["pods", "deployments", "services", "configmaps", "secrets", "namespaces"]
    verbs: ["get", "list", "watch"]